### ISSUE TITLE
前端界面一键加入歌单全部歌曲

### ISSUE THREAD

**Issue by aml123** [JumpAlang/Jusic-ui#16]
现在网站可以搜索歌单但是歌要一个一个加有点麻烦，可以增加一个一键加入所有歌单歌曲的功能，可能会方便一点？

**Comment by JumpAlang** [comment]
目前如果你是房间管理员，可以把歌单设置默认播放列表，如果点歌列表为空，会从歌单随机播放。暂不支持一键加入所有歌单 歌曲功能，以免有人点了很多歌都没去听，后面的人想点歌听不到
